FROM jupyter/base-notebook:latest

# Switch to root to install packages
USER root

RUN pip install --no-cache-dir \
    numpy pandas matplotlib scikit-learn seaborn torch tensorflow

# Restore notebook user
USER ${NB_UID}
